--liquibase formatted sql

--changeset jjuan:5

INSERT INTO SHIPS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'black pearl', now());
INSERT INTO SHIPS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'royal fortune', now());
INSERT INTO SHIPS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'css alabama', now());

INSERT INTO PORTS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_PORTS'), 'st. james', now());
INSERT INTO PORTS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_PORTS'), 'beau port', now());