--liquibase formatted sql

--changeset jjuan:5

INSERT INTO SHIPS (ID, NAME, BARRELS_OF_RUM, GOLD_COINS, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'black pearl', 10, 20, now());
INSERT INTO SHIPS (ID, NAME, BARRELS_OF_RUM, GOLD_COINS, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'royal fortune', 2, 3, now());
INSERT INTO SHIPS (ID, NAME, BARRELS_OF_RUM, GOLD_COINS, CREATION_DATE) VALUES (NEXTVAL('SEQ_SHIPS'),'css alabama', 400, 800, now());

INSERT INTO PORTS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_PORTS'), 'st. james', now());
INSERT INTO PORTS (ID, NAME, CREATION_DATE) VALUES (NEXTVAL('SEQ_PORTS'), 'beau port', now());