--liquibase formatted sql

--changeset jjuan:3

CREATE UNIQUE INDEX UX_SHIPS_ID ON SHIPS (ID);
ALTER TABLE SHIPS ADD CONSTRAINT PK_SHIPS PRIMARY KEY (ID);

CREATE UNIQUE INDEX UX_PORTS_ID ON PORTS (ID);
ALTER TABLE PORTS ADD CONSTRAINT PK_PORTS PRIMARY KEY (ID);

CREATE UNIQUE INDEX UX_EVENTS_ID ON EVENTS (ID);
ALTER TABLE EVENTS ADD CONSTRAINT PK_EVENTS PRIMARY KEY (ID);

CREATE UNIQUE INDEX UX_EVENT_TYPES_ID ON EVENT_TYPES (ID);
ALTER TABLE EVENT_TYPES ADD CONSTRAINT PK_EVENT_TYPES PRIMARY KEY (ID);

CREATE INDEX IX_SHIPS_01 ON SHIPS (CURRENT_PORT_ID);
ALTER TABLE SHIPS ADD CONSTRAINT FK_SHIPS_01 FOREIGN KEY (CURRENT_PORT_ID) REFERENCES PORTS (ID);

CREATE INDEX IX_EVENTS_01 ON EVENTS (SHIP_ID);
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_01 FOREIGN KEY (SHIP_ID) REFERENCES SHIPS (ID);

CREATE INDEX IX_EVENTS_02 ON EVENTS (PORT_ID);
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_02 FOREIGN KEY (PORT_ID) REFERENCES PORTS (ID);
